1. Import numpy

In [5]:
import numpy as np

2. 印出numpy的版本

In [ ]:
print(np.__version__)

1.21.6


3. 建立10*5的矩陣，矩陣內的數字皆為0 (5%)
*italicized text*

In [ ]:
#印出來的答案應該如下

In [ ]:
#輪到你試試看
A = np.array([
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ])
print(A)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


4.建立一個如下的矩陣:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
 (5%)

In [ ]:
#印出來的答案應該如下

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#輪到你試試看
A = np.array([
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]
    ])
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


5.建立一個5*5的單位矩陣 (5%)

In [ ]:
#印出來的答案應該如下

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#輪到你試試看
A = np.array([
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]
    ])
print(A)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


6. 做5x4與4*x3矩陣的相乘 (5%)


In [ ]:
#印出來的答案可能如下

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [ ]:
#輪到你試試看
A = np.array([
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 0]
    ])
B = np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [0, 0, 0]
    ])
print(A.dot(B))

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]]


7. 設a為[[1, 0], [1, 2]]的一個矩陣，算出矩陣的determinant (5%)


In [ ]:
#印出來的答案如下

In [ ]:
import numpy as np
from numpy import linalg as LA
a = np.array([[1, 0], [1, 2]])
det=LA.det(a)
print("Determinant of the said 2-D array:")
print(det)

Determinant of the said 2-D array:
2.0


8. 得出inverse矩陣 (5%)

In [ ]:
import numpy as np
m = np.array([
        [1, 2, 3],
        [5, 8, 9],
        [5, 8, 8],
    ])
result = np.linalg.inv(m) 
print("Original matrix:")
print(m)
print("Inverse of the said matrix:")
print(result)

Original matrix:
[[1 2 3]
 [5 8 9]
 [5 8 8]]
Inverse of the said matrix:
[[-4.   4.  -3. ]
 [ 2.5 -3.5  3. ]
 [-0.   1.  -1. ]]


In [ ]:
#印出來的參考答案如下

9. Row operations and elimination (15%)

In [2]:
#不需編撰此處code
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B  

In [4]:
G=np.array([[1,-1,1,3],[2,-2,4,8],[3,0,-9,0]])
print(G)
## Add -2 times row 0 to row 1
G1 = RowAdd(G,1,0,-2)
## Add -3 times row 0 to row 2
G2 = RowAdd(G1,2,0,-2)
## Swap rows 1 and 2
G3 = RowSwap(G2,1,2)
## Scale the new row 1 by 1/3
G4 = RowScale(G3,1,1/3)
## Scale the new row 2 by 1/2
G5 = RowScale(G4,2,1/2)
print(G5)

NameError: ignored

In [ ]:
#印出來的答案如下

10. Finding pivots (25%)

In [9]:
G=np.array([[1,-1,1,3],[2,-2,4,8],[3,0,-9,0]])
#利用第九題的def來fill the code
## Add -2 times row 0 to row 1
G1 = RowAdd(G,0,1,-2)
## Add -3 times row 0 to row 2
G2 = RowAdd(G1,0,2,-3)
## Swap rows 1 and 2
G3 = RowSwap(G2,1,2)
## Scale the new row 1 by 1/3
G4 = RowScale(G3,1,1./3)
## Scale the new row 2 by 1/2
G5 = RowScale(G4,2,1./2)
## Scale row 1 by 1/2
G3_alternative = RowScale(G2,1,1./2)
## Scale row 2 by 1/3
G4_alternative = RowScale(G3_alternative,2,1./3)
print(G4_alternative)

[[ 1. -1.  1.  3.]
 [ 0.  0.  1.  1.]
 [ 0.  1. -4. -3.]]


In [ ]:
#印出來的答案如下

11.找transpose (5%)

In [ ]:
A = np.array([[5, 4, 2],[1, 9, 3],[6, 5, 2]])
A_T = np.transpose(A)
print(A_T)

[[5 1 6]
 [4 9 5]
 [2 3 2]] 5


In [ ]:
#印出來的答案如下

12. 取出特徵向量與特徵值 (5%)

In [ ]:
import numpy as np
from numpy.linalg import eig
a = np.array([[1, 5], 
              [4, 2]])
#complete the code by yourself
(value, vector) = eig(a)
print("E-value:",value)
print("E-vector:",vector)

E-value: [-3.  6.]
E-vector: [[-0.78086881 -0.70710678]
 [ 0.62469505 -0.70710678]]


In [ ]:
#印出來的答案如下

13. 自己設計一題線性代數的題目，並用python實現 (20%，完成即13%、依題目複雜度給予給予剩下七分)

Find the best least squares fit by a linear function 𝑦 = 𝑎𝑥 + 𝑏 for the 
following data: (-1, 0), (0, 1), (1, 3)

In [ ]:
import numpy as np
A=np.array([[-1,1],[0,1],[1,1]])
B=np.array([[0],[1],[3]])
X=np.linalg.inv(np.transpose(A).dot(A)).dot(np.transpose(A)).dot(B)
print("y=",X[0,0],"x+",X[1,0])

y= 1.5 x+ 1.3333333333333333
